apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs 
    spec:
      containers:
      - name: nodeserver
        image: take1995/nodejstest:latest
        ports:
        - containerPort: 3000