apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodejs-deployment
  name: nodejs-deployment
  namespace: nodejstest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-deployment
    spec:
      containers:
      - image: take1995/nodejstest
        name: examplenodejstest
        resources: {}
status: {}