apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodejs-deployment
  name: nodejs-service
  namespace: nodejsTest
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: nodejs-deployment
  type: NodePort
status:
  loadBalancer: {}